package publish

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/theworker02/ATDE/v2/internal/config"
	"github.com/theworker02/ATDE/v2/internal/models"
	"github.com/theworker02/ATDE/v2/internal/natsbus"
)

// Publisher formats STIX/Markdown and broadcasts via community APIs you authenticate to.
type Publisher struct {
	cfg config.PublishConfig
	bus *natsbus.Bus
	log *slog.Logger
	hc  *http.Client
}

func New(cfg config.PublishConfig, bus *natsbus.Bus, log *slog.Logger) *Publisher {
	return &Publisher{
		cfg: cfg,
		bus: bus,
		log: log,
		hc:  &http.Client{Timeout: 15 * time.Second},
	}
}

func (p *Publisher) Run(ctx context.Context) error {
	if !p.cfg.Enabled {
		p.log.Info("threat intel publisher disabled")
		<-ctx.Done()
		return ctx.Err()
	}
	return p.bus.Consume(ctx, models.SubjectPublish, "PUBLISHER_DISPATCHER", "publisher_workers", p.handle)
}

func (p *Publisher) handle(data []byte) error {
	var evt models.PublishEvent
	if err := json.Unmarshal(data, &evt); err != nil {
		return fmt.Errorf("unmarshal publish: %w", err)
	}
	dry := evt.DryRun || p.cfg.DryRun
	p.log.Info("publish job", "id", evt.ID, "domain", evt.TargetDomain, "ip", evt.AttackerIP, "dry_run", dry)

	md := p.markdown(evt)
	stix := p.stixBundle(evt)
	if err := p.writeEvidence(evt.ID, md, stix); err != nil {
		p.log.Warn("evidence write", "err", err)
	}

	channels := evt.Channels
	if len(channels) == 0 {
		channels = []string{"abuseipdb", "misp", "mastodon", "bluesky", "gist"}
	}
	for _, ch := range channels {
		switch strings.ToLower(ch) {
		case "abuseipdb":
			if err := p.PostToAbuseIPDB(evt, dry); err != nil {
				p.log.Error("abuseipdb", "err", err)
			}
		case "misp":
			if err := p.PostToMISP(evt, stix, dry); err != nil {
				p.log.Error("misp", "err", err)
			}
		case "mastodon":
			if err := p.PostToMastodon(evt, dry); err != nil {
				p.log.Error("mastodon", "err", err)
			}
		case "bluesky":
			if err := p.PostToBluesky(evt, dry); err != nil {
				p.log.Error("bluesky", "err", err)
			}
		case "gist":
			if err := p.PostToGist(evt, md, stix, dry); err != nil {
				p.log.Error("gist", "err", err)
			}
		default:
			p.log.Warn("unknown publish channel", "channel", ch)
		}
	}
	return nil
}

func (p *Publisher) markdown(evt models.PublishEvent) string {
	return fmt.Sprintf(`# Automated Threat Advisory

- **ID:** %s
- **Time (UTC):** %s
- **Threat type:** %s
- **Domain:** %s
- **Attacker IP:** %s
- **Summary:** %s

## Indicators

%s

---
*Generated by ATDE Autonomous Threat Intel Publisher*
`,
		evt.ID, evt.Timestamp.Format(time.RFC3339), evt.ThreatType, evt.TargetDomain, evt.AttackerIP, evt.Summary,
		strings.Join(prefixIOC(evt.IOCs), "\n"),
	)
}

func prefixIOC(iocs []string) []string {
	out := make([]string, 0, len(iocs))
	for _, i := range iocs {
		out = append(out, "- `"+i+"`")
	}
	return out
}

func (p *Publisher) stixBundle(evt models.PublishEvent) map[string]any {
	now := evt.Timestamp.UTC().Format(time.RFC3339)
	if evt.Timestamp.IsZero() {
		now = time.Now().UTC().Format(time.RFC3339)
	}
	objects := []map[string]any{
		{
			"type":         "indicator",
			"spec_version": "2.1",
			"id":           "indicator--" + sanitizeID(evt.ID),
			"created":      now,
			"modified":     now,
			"name":         evt.ThreatType + " — " + evt.TargetDomain,
			"description":  evt.Summary,
			"pattern":      buildSTIXPattern(evt),
			"pattern_type": "stix",
			"valid_from":   now,
			"labels":       []string{"atde", "automated", evt.ThreatType},
		},
	}
	if evt.AttackerIP != "" {
		objects = append(objects, map[string]any{
			"type":         "ipv4-addr",
			"spec_version": "2.1",
			"id":           "ipv4-addr--" + sanitizeID(evt.AttackerIP),
			"value":        evt.AttackerIP,
		})
	}
	if evt.TargetDomain != "" && evt.TargetDomain != "honeypot-capture" {
		objects = append(objects, map[string]any{
			"type":         "domain-name",
			"spec_version": "2.1",
			"id":           "domain-name--" + sanitizeID(evt.TargetDomain),
			"value":        evt.TargetDomain,
		})
	}
	return map[string]any{
		"type":        "bundle",
		"id":          "bundle--" + sanitizeID(evt.ID),
		"objects":     objects,
	}
}

func buildSTIXPattern(evt models.PublishEvent) string {
	var parts []string
	if evt.AttackerIP != "" {
		parts = append(parts, fmt.Sprintf("[ipv4-addr:value = '%s']", evt.AttackerIP))
	}
	if evt.TargetDomain != "" && evt.TargetDomain != "honeypot-capture" {
		parts = append(parts, fmt.Sprintf("[domain-name:value = '%s']", evt.TargetDomain))
	}
	if len(parts) == 0 {
		return "[x-atde:id = '" + evt.ID + "']"
	}
	return strings.Join(parts, " OR ")
}

func sanitizeID(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	out := b.String()
	if len(out) > 64 {
		out = out[:64]
	}
	return out
}

func (p *Publisher) writeEvidence(id, md string, stix map[string]any) error {
	dir := p.cfg.EvidenceDir
	if dir == "" {
		dir = "./data/evidence"
	}
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, id+"-advisory.md"), []byte(md), 0o600); err != nil {
		return err
	}
	raw, _ := json.MarshalIndent(stix, "", "  ")
	return os.WriteFile(filepath.Join(dir, id+"-stix21.json"), raw, 0o600)
}

func (p *Publisher) PostToAbuseIPDB(evt models.PublishEvent, dry bool) error {
	ip := strings.TrimSpace(evt.AttackerIP)
	if ip == "" {
		p.log.Info("abuseipdb skip: no attacker ip", "id", evt.ID)
		return nil
	}
	key := first(p.cfg.AbuseIPDBKey, os.Getenv("ABUSEIPDB_API_KEY"))
	comment := fmt.Sprintf("Automated report by ATDE. Identified %s targeting %s. %s", evt.ThreatType, evt.TargetDomain, evt.Summary)
	cats := evt.AbuseIPDBCategories
	if len(cats) == 0 {
		cats = []int{11, 18} // phishing, brute-force
	}
	if dry || key == "" {
		p.log.Info("abuseipdb dry-run/skip", "ip", ip, "categories", cats, "key_set", key != "")
		return nil
	}
	form := url.Values{}
	form.Set("ip", ip)
	form.Set("categories", joinInts(cats))
	form.Set("comment", truncate(comment, 1000))
	req, err := http.NewRequest(http.MethodPost, "https://api.abuseipdb.com/api/v2/report", strings.NewReader(form.Encode()))
	if err != nil {
		return err
	}
	req.Header.Set("Key", key)
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := p.hc.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<16))
	if resp.StatusCode == http.StatusOK {
		p.log.Info("reported to abuseipdb", "ip", ip)
		return nil
	}
	return fmt.Errorf("status %d: %s", resp.StatusCode, truncate(string(body), 200))
}

func (p *Publisher) PostToMISP(evt models.PublishEvent, stix map[string]any, dry bool) error {
	base := first(p.cfg.MISPURL, os.Getenv("MISP_URL"))
	key := first(p.cfg.MISPKey, os.Getenv("MISP_API_KEY"))
	if dry || base == "" || key == "" {
		p.log.Info("misp dry-run/skip", "event", evt.ID, "url_set", base != "")
		return nil
	}
	endpoint := strings.TrimRight(base, "/") + "/events/add"
	payload := map[string]any{
		"Event": map[string]any{
			"info":           evt.ThreatType + " — " + evt.TargetDomain,
			"threat_level_id": "2",
			"analysis":       "1",
			"distribution":   "1",
			"Attribute":      mispAttrs(evt),
		},
		"stix": stix,
	}
	raw, _ := json.Marshal(payload)
	req, err := http.NewRequest(http.MethodPost, endpoint, bytes.NewReader(raw))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", key)
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Content-Type", "application/json")
	resp, err := p.hc.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		p.log.Info("misp event created", "id", evt.ID)
		return nil
	}
	b, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<14))
	return fmt.Errorf("misp status %d: %s", resp.StatusCode, truncate(string(b), 200))
}

func mispAttrs(evt models.PublishEvent) []map[string]any {
	var attrs []map[string]any
	if evt.AttackerIP != "" {
		attrs = append(attrs, map[string]any{"type": "ip-src", "value": evt.AttackerIP, "category": "Network activity"})
	}
	if evt.TargetDomain != "" && evt.TargetDomain != "honeypot-capture" {
		attrs = append(attrs, map[string]any{"type": "domain", "value": evt.TargetDomain, "category": "Network activity"})
	}
	for _, ioc := range evt.IOCs {
		attrs = append(attrs, map[string]any{"type": "text", "value": ioc, "category": "Other"})
	}
	return attrs
}

func (p *Publisher) PostToMastodon(evt models.PublishEvent, dry bool) error {
	token := first(p.cfg.MastodonToken, os.Getenv("MASTODON_ACCESS_TOKEN"))
	inst := first(p.cfg.MastodonInstance, os.Getenv("MASTODON_INSTANCE_URL"))
	status := fmt.Sprintf("🚨 [AUTOMATED THREAT ADVISORY]\nType: %s\nDomain: %s\nAttacker IP: %s\nSummary: %s\n#CyberSecurity #ThreatIntel #BotnetDisruption",
		evt.ThreatType, evt.TargetDomain, evt.AttackerIP, truncate(evt.Summary, 200))
	if dry || token == "" || inst == "" {
		p.log.Info("mastodon advisory drafted", "status_preview", truncate(status, 160), "configured", token != "" && inst != "")
		return nil
	}
	endpoint := strings.TrimRight(inst, "/") + "/api/v1/statuses"
	body, _ := json.Marshal(map[string]string{"status": status})
	req, err := http.NewRequest(http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")
	resp, err := p.hc.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusOK || resp.StatusCode == http.StatusCreated {
		p.log.Info("mastodon broadcast ok", "domain", evt.TargetDomain)
		return nil
	}
	return fmt.Errorf("mastodon status %d", resp.StatusCode)
}

func (p *Publisher) PostToBluesky(evt models.PublishEvent, dry bool) error {
	// Prefer webhook; full AT Proto session login is optional via BLUESKY_POST_WEBHOOK.
	hook := first(p.cfg.BlueskyWebhook, os.Getenv("BLUESKY_POST_WEBHOOK"))
	text := fmt.Sprintf("[ATDE] %s | %s | IP %s | %s", evt.ThreatType, evt.TargetDomain, evt.AttackerIP, truncate(evt.Summary, 180))
	if dry || hook == "" {
		p.log.Info("bluesky advisory drafted", "text", truncate(text, 160), "webhook_set", hook != "")
		return nil
	}
	body, _ := json.Marshal(map[string]string{"text": text, "source": "atde"})
	resp, err := p.hc.Post(hook, "application/json", bytes.NewReader(body))
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		p.log.Info("bluesky broadcast ok", "domain", evt.TargetDomain)
		return nil
	}
	return fmt.Errorf("bluesky webhook status %d", resp.StatusCode)
}

func (p *Publisher) PostToGist(evt models.PublishEvent, md string, stix map[string]any, dry bool) error {
	token := first(p.cfg.GitHubToken, os.Getenv("GITHUB_TOKEN"))
	stixRaw, _ := json.MarshalIndent(stix, "", "  ")
	if dry || token == "" {
		p.log.Info("gist dry-run/skip", "id", evt.ID, "token_set", token != "")
		return nil
	}
	payload := map[string]any{
		"description": "ATDE threat advisory " + evt.ID,
		"public":      false,
		"files": map[string]any{
			"advisory.md":     map[string]string{"content": md},
			"indicators.stix": map[string]string{"content": string(stixRaw)},
		},
	}
	raw, _ := json.Marshal(payload)
	req, err := http.NewRequest(http.MethodPost, "https://api.github.com/gists", bytes.NewReader(raw))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("Content-Type", "application/json")
	resp, err := p.hc.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<16))
	if resp.StatusCode == http.StatusCreated || resp.StatusCode == http.StatusOK {
		var out struct {
			HTMLURL string `json:"html_url"`
		}
		_ = json.Unmarshal(body, &out)
		p.log.Info("gist created", "url", out.HTMLURL)
		return nil
	}
	return fmt.Errorf("gist status %d: %s", resp.StatusCode, truncate(string(body), 200))
}

func joinInts(xs []int) string {
	parts := make([]string, len(xs))
	for i, v := range xs {
		parts[i] = fmt.Sprintf("%d", v)
	}
	return strings.Join(parts, ",")
}

func first(vals ...string) string {
	for _, v := range vals {
		if strings.TrimSpace(v) != "" {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

// MarkdownForTest / STIXForTest expose formatters for unit tests.
func (p *Publisher) MarkdownForTest(evt models.PublishEvent) string { return p.markdown(evt) }
func (p *Publisher) STIXForTest(evt models.PublishEvent) map[string]any {
	return p.stixBundle(evt)
}
