package dispatcher

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/theworker02/blind-botnet/v2/internal/models"
	"github.com/theworker02/blind-botnet/v2/internal/natsbus"
)

// Service consumes threat.v1.action.takedown and dispatches abuse packages.
type Service struct {
	bus         *natsbus.Bus
	log         *slog.Logger
	hc          *http.Client
	evidenceDir string
	dryRun      bool
	gsbKey      string
}

func New(bus *natsbus.Bus, evidenceDir string, dryRun bool, log *slog.Logger) *Service {
	return &Service{
		bus:         bus,
		log:         log,
		hc:          &http.Client{Timeout: 30 * time.Second},
		evidenceDir: evidenceDir,
		dryRun:      dryRun,
		gsbKey:      os.Getenv("GOOGLE_SAFE_BROWSING_API_KEY"),
	}
}

func (s *Service) Run(ctx context.Context) error {
	return s.bus.Consume(ctx, models.SubjectTakedown, "TAKEDOWN_DISPATCHER", "takedown_workers", s.handle)
}

func (s *Service) handle(data []byte) error {
	var evt models.TakedownEvent
	if err := json.Unmarshal(data, &evt); err != nil {
		return fmt.Errorf("unmarshal takedown: %w", err)
	}
	dry := s.dryRun || evt.DryRun
	s.log.Info("processing takedown", "id", evt.ID, "domain", evt.Target.Domain, "dry_run", dry)

	report := s.GenerateMarkdownEvidence(evt)
	path, err := s.saveReport(evt.ID, report)
	if err != nil {
		s.log.Warn("evidence save failed", "err", err)
	} else {
		s.log.Info("evidence written", "path", path)
	}

	for _, target := range evt.DispatchTargets {
		switch target {
		case "google_safe_browsing":
			if err := s.submitGoogleSafeBrowsing(evt.EvidenceSummary.HarvesterURL, dry); err != nil {
				s.log.Error("safebrowsing dispatch failed", "err", err)
			}
		case "hosting_provider_abuse_api":
			s.dispatchHostingAbuse(evt, report, dry)
		case "cloudflare_abuse":
			s.dispatchCloudflare(evt, report, dry)
		default:
			s.log.Warn("unknown dispatch target", "target", target)
		}
	}
	return nil
}

// GenerateMarkdownEvidence builds a standardized abuse notice.
func (s *Service) GenerateMarkdownEvidence(evt models.TakedownEvent) string {
	return fmt.Sprintf(`# AUTOMATED ABUSE NOTICE & TAKEDOWN REQUEST
**Notice Identifier:** %s
**Generated At:** %s
**Target Domain:** %s
**IP Address:** %s (ASN: %s)

---

### Incident Summary
Our automated threat intelligence engine identified active cybercriminal infrastructure hosted on your network. The target host is serving active phishing/credential harvesting software targeting enterprise entities.

### Technical Proof & Evidence
- **Target URL:** %s
- **Classification:** %s
- **Exfiltration Vector Identified:** %s
- **Evidence PCAP SHA-256:** %s
- **Registrar Hint:** %s
- **Hosting Provider:** %s

### Legal Action Requested
Pursuant to applicable computer crime regulations and your network Acceptable Use Policy (AUP), we request that you:
1. Suspend the domain/IP routing for target host %s.
2. Preserve logs and forensic artifacts related to account/IP %s for law enforcement review.

*This report was generated by an Active Defense System (ATDE). Dry-run=%v*
`,
		evt.ID, evt.Timestamp.Format(time.RFC3339), evt.Target.Domain, evt.Target.IP, evt.Target.ASN,
		evt.EvidenceSummary.HarvesterURL, evt.EvidenceSummary.Title, evt.EvidenceSummary.ExfiltrationMethod,
		evt.EvidenceSummary.PCAPHashSHA256, evt.Target.Registrar, evt.Target.HostingProvider,
		evt.Target.Domain, evt.Target.IP, s.dryRun || evt.DryRun,
	)
}

func (s *Service) saveReport(id, text string) (string, error) {
	if err := os.MkdirAll(s.evidenceDir, 0o750); err != nil {
		return "", err
	}
	path := filepath.Join(s.evidenceDir, id+"-abuse-report.md")
	return path, os.WriteFile(path, []byte(text), 0o600)
}

// submitGoogleSafeBrowsing looks up / reports via configured endpoints.
// Note: threatMatches:find is a LOOKUP API, not a submission API. Live reporting
// uses GOOGLE_SB_REPORT_ENDPOINT when set; otherwise dry-run logs the intent.
func (s *Service) submitGoogleSafeBrowsing(targetURL string, dry bool) error {
	if dry {
		s.log.Info("dry-run: would submit to Safe Browsing report channel", "url", targetURL)
		return nil
	}
	reportEP := os.Getenv("GOOGLE_SB_REPORT_ENDPOINT")
	if reportEP != "" {
		payload, _ := json.Marshal(map[string]any{
			"url":    targetURL,
			"source": "atde",
		})
		req, err := http.NewRequest(http.MethodPost, reportEP, bytes.NewReader(payload))
		if err != nil {
			return err
		}
		req.Header.Set("Content-Type", "application/json")
		if s.gsbKey != "" {
			req.Header.Set("Authorization", "Bearer "+s.gsbKey)
		}
		resp, err := s.hc.Do(req)
		if err != nil {
			return err
		}
		defer resp.Body.Close()
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<16))
		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
			s.log.Info("submitted to Safe Browsing report endpoint", "url", targetURL)
			return nil
		}
		return fmt.Errorf("report endpoint status %d: %s", resp.StatusCode, truncate(string(body), 200))
	}

	// Optional advisory lookup (does not submit new threats).
	if s.gsbKey == "" {
		return fmt.Errorf("GOOGLE_SAFE_BROWSING_API_KEY / GOOGLE_SB_REPORT_ENDPOINT missing")
	}
	apiEndpoint := fmt.Sprintf("https://safebrowsing.googleapis.com/v4/threatMatches:find?key=%s", s.gsbKey)
	payload := map[string]any{
		"client": map[string]string{
			"clientId":      "autonomous-disruption-engine",
			"clientVersion": "1.0.0",
		},
		"threatInfo": map[string]any{
			"threatTypes":      []string{"SOCIAL_ENGINEERING", "MALWARE"},
			"platformTypes":    []string{"ANY_PLATFORM"},
			"threatEntryTypes": []string{"URL"},
			"threatEntries":    []map[string]string{{"url": targetURL}},
		},
	}
	body, _ := json.Marshal(payload)
	resp, err := s.hc.Post(apiEndpoint, "application/json", bytes.NewBuffer(body))
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	respBody, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<16))
	s.log.Info("Safe Browsing lookup complete (not a submission)", "url", targetURL, "status", resp.StatusCode, "body", truncate(string(respBody), 200))
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("API returned non-200 status: %d", resp.StatusCode)
	}
	return nil
}

func (s *Service) dispatchHostingAbuse(evt models.TakedownEvent, report string, dry bool) {
	if dry {
		s.log.Info("dry-run: hosting abuse ticket",
			"provider", evt.Target.HostingProvider,
			"ip", evt.Target.IP,
			"domain", evt.Target.Domain,
		)
		return
	}
	endpoint := os.Getenv("HOSTING_ABUSE_API_URL")
	if endpoint == "" {
		s.log.Warn("HOSTING_ABUSE_API_URL not set; skipping live hosting dispatch")
		return
	}
	payload, _ := json.Marshal(map[string]any{
		"domain":   evt.Target.Domain,
		"ip":       evt.Target.IP,
		"provider": evt.Target.HostingProvider,
		"report":   report,
		"id":       evt.ID,
	})
	resp, err := s.hc.Post(endpoint, "application/json", bytes.NewReader(payload))
	if err != nil {
		s.log.Error("hosting abuse post failed", "err", err)
		return
	}
	defer resp.Body.Close()
	s.log.Info("hosting abuse dispatched", "status", resp.StatusCode, "provider", evt.Target.HostingProvider)
}

func (s *Service) dispatchCloudflare(evt models.TakedownEvent, report string, dry bool) {
	if dry {
		s.log.Info("dry-run: cloudflare abuse", "domain", evt.Target.Domain)
		return
	}
	endpoint := os.Getenv("CLOUDFLARE_ABUSE_API_URL")
	token := os.Getenv("CLOUDFLARE_API_TOKEN")
	if endpoint == "" {
		s.log.Warn("CLOUDFLARE_ABUSE_API_URL not set; skipping")
		return
	}
	payload, _ := json.Marshal(map[string]any{
		"domains": []string{evt.Target.Domain},
		"report":  report,
		"id":      evt.ID,
	})
	req, err := http.NewRequest(http.MethodPost, endpoint, bytes.NewReader(payload))
	if err != nil {
		s.log.Error("cloudflare request", "err", err)
		return
	}
	req.Header.Set("Content-Type", "application/json")
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	resp, err := s.hc.Do(req)
	if err != nil {
		s.log.Error("cloudflare dispatch failed", "err", err)
		return
	}
	defer resp.Body.Close()
	s.log.Info("cloudflare abuse submitted", "status", resp.StatusCode, "domain", evt.Target.Domain)
}

func truncate(s string, n int) string {
	s = strings.TrimSpace(s)
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
