package catch

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// GetDossier loads dossier_<IP>.json if present.
func (l *Ledger) GetDossier(ip string) (*Dossier, error) {
	if l == nil {
		return nil, fmt.Errorf("catch: nil ledger")
	}
	ip = StripPort(ip)
	path := filepath.Join(l.Dir, "dossier_"+sanitize(ip)+".json")
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var d Dossier
	if err := json.Unmarshal(raw, &d); err != nil {
		return nil, err
	}
	return &d, nil
}

// ListDossiers returns dossiers sorted by last_seen descending (newest first).
func (l *Ledger) ListDossiers(limit int) ([]Dossier, error) {
	if l == nil {
		return nil, nil
	}
	if limit <= 0 {
		limit = 100
	}
	entries, err := os.ReadDir(l.Dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var out []Dossier
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasPrefix(name, "dossier_") || !strings.HasSuffix(name, ".json") {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(l.Dir, name))
		if err != nil {
			continue
		}
		var d Dossier
		if err := json.Unmarshal(raw, &d); err != nil {
			continue
		}
		out = append(out, d)
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].LastSeen.After(out[j].LastSeen)
	})
	if len(out) > limit {
		out = out[:limit]
	}
	return out, nil
}

// ListByIP returns recent events for one IP (newest last, then truncated from start).
func (l *Ledger) ListByIP(ip string, limit int) ([]Record, error) {
	ip = StripPort(ip)
	if ip == "" {
		return nil, fmt.Errorf("catch: missing ip")
	}
	recs, err := l.ListRecent(10_000)
	if err != nil {
		return nil, err
	}
	var out []Record
	for _, r := range recs {
		if r.IP == ip {
			out = append(out, r)
		}
	}
	if limit <= 0 {
		limit = 100
	}
	if len(out) > limit {
		out = out[len(out)-limit:]
	}
	return out, nil
}

// ExportMarkdown builds an abuse-ready package for one IP.
func (l *Ledger) ExportMarkdown(ip string) (string, error) {
	d, err := l.GetDossier(ip)
	if err != nil {
		return "", err
	}
	recs, _ := l.ListByIP(ip, 100)
	var b strings.Builder
	fmt.Fprintf(&b, "# ATDE catch package — %s\n\n", d.IP)
	fmt.Fprintf(&b, "**Product:** Autonomous Threat Disruption Engine (ATDE) 1.3  \n")
	fmt.Fprintf(&b, "**Classification:** Defensive honeypot evidence — operator-owned decoy  \n")
	fmt.Fprintf(&b, "**Generated:** %s\n\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "## Subject\n\n")
	fmt.Fprintf(&b, "Observed scanning / credential abuse against an **ATDE decoy** under the reporting operator’s control. This is not a report of compromise of production customer data.\n\n")
	fmt.Fprintf(&b, "## Summary table\n\n")
	fmt.Fprintf(&b, "| Field | Value |\n|-------|-------|\n")
	fmt.Fprintf(&b, "| Source IP | `%s` |\n", d.IP)
	fmt.Fprintf(&b, "| First seen (UTC) | %s |\n", d.FirstSeen.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "| Last seen (UTC) | %s |\n", d.LastSeen.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "| Hit count | %d |\n", d.HitCount)
	fmt.Fprintf(&b, "| Max severity (0–100) | %d |\n", d.MaxSeverity)
	fmt.Fprintf(&b, "| Tools | %s |\n", strings.Join(d.Tools, ", "))
	fmt.Fprintf(&b, "| Tags | %s |\n", strings.Join(d.Tags, ", "))
	fmt.Fprintf(&b, "| Last activity | %s |\n", d.LastSummary)
	fmt.Fprintf(&b, "| Local block applied | %v |\n", d.Blocked)
	fmt.Fprintf(&b, "| Private/TEST-NET | %v |\n", d.PrivateIP)
	fmt.Fprintf(&b, "| Sources | %s |\n", strings.Join(d.Sources, ", "))
	fmt.Fprintf(&b, "| Services | %s |\n", strings.Join(d.Services, ", "))
	fmt.Fprintf(&b, "| Paths | %s |\n", strings.Join(capSlice(d.Paths, 20), ", "))
	fmt.Fprintf(&b, "| Reasons | %s |\n", strings.Join(d.Reasons, ", "))
	fmt.Fprintf(&b, "| Actions | %s |\n\n", strings.Join(d.Actions, ", "))
	if len(d.UserAgents) > 0 {
		b.WriteString("## User-Agents\n\n")
		for _, ua := range d.UserAgents {
			fmt.Fprintf(&b, "- `%s`\n", ua)
		}
		b.WriteString("\n")
	}
	if len(recs) > 0 {
		b.WriteString("## Timeline (recent events)\n\n")
		b.WriteString("| UTC | Service | Method | Path | Severity | Detail |\n")
		b.WriteString("|-----|---------|--------|------|----------|--------|\n")
		for _, r := range recs {
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %d | %s |\n",
				r.CaughtAt.UTC().Format(time.RFC3339), r.Service, r.Method, r.Path, r.Severity, escapeMD(r.Summary+" "+r.Reason))
		}
		b.WriteString("\n")
	}
	b.WriteString("## Recommended recipient actions\n\n")
	b.WriteString("1. Correlate source IP against your abuse / peering records.\n")
	b.WriteString("2. If confirmed malicious, apply network-level blocks or rate limits.\n")
	b.WriteString("3. Optional: ingest accompanying STIX 2.1 (`atde-<ip>.stix.json`) into your TIP.\n\n")
	b.WriteString("---\n*Defensive evidence only. Generated by ATDE. Operator owns the decoy host.*\n")
	return b.String(), nil
}

func escapeMD(s string) string {
	s = strings.ReplaceAll(s, "|", "/")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.TrimSpace(s)
}

// OnRecord is invoked after a successful ledger write (optional).
type OnRecord func(r Record)

// WithHook attaches a post-record callback (e.g. webhook notifier).
func (l *Ledger) WithHook(fn OnRecord) *Ledger {
	if l == nil {
		return l
	}
	l.hook = fn
	return l
}
